//
// Copyright 2020-2026 Swiftkube Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

//
// Generated by Swiftkube:ModelGen
// Kubernetes v1.34.6
// core.v1.ContainerExtendedResourceRequest
//

import Foundation

// MARK: - core.v1.ContainerExtendedResourceRequest

public extension core.v1 {

	///
	/// ContainerExtendedResourceRequest has the mapping of container name, extended resource name to the device request name.
	///
	struct ContainerExtendedResourceRequest: KubernetesResource {
		///
		/// The name of the container requesting resources.
		///
		public var containerName: String
		///
		/// The name of the request in the special ResourceClaim which corresponds to the extended resource.
		///
		public var requestName: String
		///
		/// The name of the extended resource in that container which gets backed by DRA.
		///
		public var resourceName: String
		///
		/// Default memberwise initializer
		///
		public init(
			containerName: String,
			requestName: String,
			resourceName: String
		) {
			self.containerName = containerName
			self.requestName = requestName
			self.resourceName = resourceName
		}
	}
}

///
/// Codable conformance
///
public extension core.v1.ContainerExtendedResourceRequest {

	private enum CodingKeys: String, CodingKey {

		case containerName = "containerName"
		case requestName = "requestName"
		case resourceName = "resourceName"
	}

	init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		self.containerName = try container.decode(String.self, forKey: .containerName)
		self.requestName = try container.decode(String.self, forKey: .requestName)
		self.resourceName = try container.decode(String.self, forKey: .resourceName)
	}

	func encode(to encoder: Encoder) throws {
		var encodingContainer = encoder.container(keyedBy: CodingKeys.self)

		try encodingContainer.encode(containerName, forKey: .containerName)
		try encodingContainer.encode(requestName, forKey: .requestName)
		try encodingContainer.encode(resourceName, forKey: .resourceName)
	}
}
