//
// Copyright 2020-2026 Swiftkube Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

//
// Generated by Swiftkube:ModelGen
// Kubernetes v1.34.6
// core.v1.ContainerRestartRule
//

import Foundation

// MARK: - core.v1.ContainerRestartRule

public extension core.v1 {

	///
	/// ContainerRestartRule describes how a container exit is handled.
	///
	struct ContainerRestartRule: KubernetesResource {
		///
		/// Specifies the action taken on a container exit if the requirements are satisfied. The only possible value is "Restart" to restart the container.
		///
		public var action: String
		///
		/// Represents the exit codes to check on container exits.
		///
		public var exitCodes: core.v1.ContainerRestartRuleOnExitCodes?
		///
		/// Default memberwise initializer
		///
		public init(
			action: String,
			exitCodes: core.v1.ContainerRestartRuleOnExitCodes? = nil
		) {
			self.action = action
			self.exitCodes = exitCodes
		}
	}
}

///
/// Codable conformance
///
public extension core.v1.ContainerRestartRule {

	private enum CodingKeys: String, CodingKey {

		case action = "action"
		case exitCodes = "exitCodes"
	}

	init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		self.action = try container.decode(String.self, forKey: .action)
		self.exitCodes = try container.decodeIfPresent(core.v1.ContainerRestartRuleOnExitCodes.self, forKey: .exitCodes)
	}

	func encode(to encoder: Encoder) throws {
		var encodingContainer = encoder.container(keyedBy: CodingKeys.self)

		try encodingContainer.encode(action, forKey: .action)
		try encodingContainer.encode(exitCodes, forKey: .exitCodes)
	}
}
