//
// Copyright 2020 Iskandar Abudiab (iabudiab.dev)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

///
/// Generated by Swiftkube:ModelGen
/// Kubernetes v1.18.13
/// core.v1.NamespaceStatus
///

import Foundation

public extension core.v1 {

	///
	/// NamespaceStatus is information about the current status of a Namespace.
	///
	struct NamespaceStatus: KubernetesResource {
		///
		/// Represents the latest available observations of a namespace's current state.
		///
		public var conditions: [core.v1.NamespaceCondition]?
		///
		/// Phase is the current lifecycle phase of the namespace. More info: https://kubernetes.io/docs/tasks/administer-cluster/namespaces/
		///
		public var phase: String?
		///
		/// Default memberwise initializer
		///
		public init(
			conditions: [core.v1.NamespaceCondition]? = nil,
			phase: String? = nil
		) {
			self.conditions = conditions
			self.phase = phase
		}
	}
}

///
/// Codable conformance
///
extension core.v1.NamespaceStatus {

	private enum CodingKeys: String, CodingKey {

		case conditions = "conditions"
		case phase = "phase"
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		self.conditions = try container.decodeIfPresent([core.v1.NamespaceCondition].self, forKey: .conditions)
		self.phase = try container.decodeIfPresent(String.self, forKey: .phase)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)

		try container.encode(self.conditions, forKey: .conditions)
		try container.encode(self.phase, forKey: .phase)
	}

}

