//
// Copyright 2020 Swiftkube Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

///
/// Generated by Swiftkube:ModelGen
/// Kubernetes v1.32.0
/// core.v1.PersistentVolumeClaimSpec
///

import Foundation

// MARK: - core.v1.PersistentVolumeClaimSpec

public extension core.v1 {

	///
	/// PersistentVolumeClaimSpec describes the common attributes of storage devices and allows a Source for provider-specific attributes
	///
	struct PersistentVolumeClaimSpec: KubernetesResource {
		///
		/// accessModes contains the desired access modes the volume should have. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1
		///
		public var accessModes: [String]?
		///
		/// dataSource field can be used to specify either: * An existing VolumeSnapshot object (snapshot.storage.k8s.io/VolumeSnapshot) * An existing PVC (PersistentVolumeClaim) If the provisioner or an external controller can support the specified data source, it will create a new volume based on the contents of the specified data source. When the AnyVolumeDataSource feature gate is enabled, dataSource contents will be copied to dataSourceRef, and dataSourceRef contents will be copied to dataSource when dataSourceRef.namespace is not specified. If the namespace is specified, then dataSourceRef will not be copied to dataSource.
		///
		public var dataSource: core.v1.TypedLocalObjectReference?
		///
		/// dataSourceRef specifies the object from which to populate the volume with data, if a non-empty volume is desired. This may be any object from a non-empty API group (non core object) or a PersistentVolumeClaim object. When this field is specified, volume binding will only succeed if the type of the specified object matches some installed volume populator or dynamic provisioner. This field will replace the functionality of the dataSource field and as such if both fields are non-empty, they must have the same value. For backwards compatibility, when namespace isn't specified in dataSourceRef, both fields (dataSource and dataSourceRef) will be set to the same value automatically if one of them is empty and the other is non-empty. When namespace is specified in dataSourceRef, dataSource isn't set to the same value and must be empty. There are three important differences between dataSource and dataSourceRef: * While dataSource only allows two specific types of objects, dataSourceRef
		///   allows any non-core object, as well as PersistentVolumeClaim objects.
		/// * While dataSource ignores disallowed values (dropping them), dataSourceRef
		///   preserves all values, and generates an error if a disallowed value is
		///   specified.
		/// * While dataSource only allows local objects, dataSourceRef allows objects
		///   in any namespaces.
		/// (Beta) Using this field requires the AnyVolumeDataSource feature gate to be enabled. (Alpha) Using the namespace field of dataSourceRef requires the CrossNamespaceVolumeDataSource feature gate to be enabled.
		///
		public var dataSourceRef: core.v1.TypedObjectReference?
		///
		/// resources represents the minimum resources the volume should have. If RecoverVolumeExpansionFailure feature is enabled users are allowed to specify resource requirements that are lower than previous value but must still be higher than capacity recorded in the status field of the claim. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#resources
		///
		public var resources: core.v1.VolumeResourceRequirements?
		///
		/// selector is a label query over volumes to consider for binding.
		///
		public var selector: meta.v1.LabelSelector?
		///
		/// storageClassName is the name of the StorageClass required by the claim. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#class-1
		///
		public var storageClassName: String?
		///
		/// volumeAttributesClassName may be used to set the VolumeAttributesClass used by this claim. If specified, the CSI driver will create or update the volume with the attributes defined in the corresponding VolumeAttributesClass. This has a different purpose than storageClassName, it can be changed after the claim is created. An empty string value means that no VolumeAttributesClass will be applied to the claim but it's not allowed to reset this field to empty string once it is set. If unspecified and the PersistentVolumeClaim is unbound, the default VolumeAttributesClass will be set by the persistentvolume controller if it exists. If the resource referred to by volumeAttributesClass does not exist, this PersistentVolumeClaim will be set to a Pending state, as reflected by the modifyVolumeStatus field, until such as a resource exists. More info: https://kubernetes.io/docs/concepts/storage/volume-attributes-classes/ (Beta) Using this field requires the VolumeAttributesClass feature gate to be enabled (off by default).
		///
		public var volumeAttributesClassName: String?
		///
		/// volumeMode defines what type of volume is required by the claim. Value of Filesystem is implied when not included in claim spec.
		///
		public var volumeMode: String?
		///
		/// volumeName is the binding reference to the PersistentVolume backing this claim.
		///
		public var volumeName: String?
		///
		/// Default memberwise initializer
		///
		public init(
			accessModes: [String]? = nil,
			dataSource: core.v1.TypedLocalObjectReference? = nil,
			dataSourceRef: core.v1.TypedObjectReference? = nil,
			resources: core.v1.VolumeResourceRequirements? = nil,
			selector: meta.v1.LabelSelector? = nil,
			storageClassName: String? = nil,
			volumeAttributesClassName: String? = nil,
			volumeMode: String? = nil,
			volumeName: String? = nil
		) {
			self.accessModes = accessModes
			self.dataSource = dataSource
			self.dataSourceRef = dataSourceRef
			self.resources = resources
			self.selector = selector
			self.storageClassName = storageClassName
			self.volumeAttributesClassName = volumeAttributesClassName
			self.volumeMode = volumeMode
			self.volumeName = volumeName
		}
	}
}

///
/// Codable conformance
///
public extension core.v1.PersistentVolumeClaimSpec {

	private enum CodingKeys: String, CodingKey {

		case accessModes = "accessModes"
		case dataSource = "dataSource"
		case dataSourceRef = "dataSourceRef"
		case resources = "resources"
		case selector = "selector"
		case storageClassName = "storageClassName"
		case volumeAttributesClassName = "volumeAttributesClassName"
		case volumeMode = "volumeMode"
		case volumeName = "volumeName"
	}

	init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		self.accessModes = try container.decodeIfPresent([String].self, forKey: .accessModes)
		self.dataSource = try container.decodeIfPresent(core.v1.TypedLocalObjectReference.self, forKey: .dataSource)
		self.dataSourceRef = try container.decodeIfPresent(core.v1.TypedObjectReference.self, forKey: .dataSourceRef)
		self.resources = try container.decodeIfPresent(core.v1.VolumeResourceRequirements.self, forKey: .resources)
		self.selector = try container.decodeIfPresent(meta.v1.LabelSelector.self, forKey: .selector)
		self.storageClassName = try container.decodeIfPresent(String.self, forKey: .storageClassName)
		self.volumeAttributesClassName = try container.decodeIfPresent(String.self, forKey: .volumeAttributesClassName)
		self.volumeMode = try container.decodeIfPresent(String.self, forKey: .volumeMode)
		self.volumeName = try container.decodeIfPresent(String.self, forKey: .volumeName)
	}

	func encode(to encoder: Encoder) throws {
		var encodingContainer = encoder.container(keyedBy: CodingKeys.self)

		try encodingContainer.encode(accessModes, forKey: .accessModes)
		try encodingContainer.encode(dataSource, forKey: .dataSource)
		try encodingContainer.encode(dataSourceRef, forKey: .dataSourceRef)
		try encodingContainer.encode(resources, forKey: .resources)
		try encodingContainer.encode(selector, forKey: .selector)
		try encodingContainer.encode(storageClassName, forKey: .storageClassName)
		try encodingContainer.encode(volumeAttributesClassName, forKey: .volumeAttributesClassName)
		try encodingContainer.encode(volumeMode, forKey: .volumeMode)
		try encodingContainer.encode(volumeName, forKey: .volumeName)
	}
}
