//
// Copyright 2020-2026 Swiftkube Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

//
// Generated by Swiftkube:ModelGen
// Kubernetes v1.34.6
// certificates.v1alpha1.PodCertificateRequestSpec
//

import Foundation

// MARK: - certificates.v1alpha1.PodCertificateRequestSpec

public extension certificates.v1alpha1 {

	///
	/// PodCertificateRequestSpec describes the certificate request.  All fields are immutable after creation.
	///
	struct PodCertificateRequestSpec: KubernetesResource {
		///
		/// maxExpirationSeconds is the maximum lifetime permitted for the certificate.
		///
		/// If omitted, kube-apiserver will set it to 86400(24 hours). kube-apiserver will reject values shorter than 3600 (1 hour).  The maximum allowable value is 7862400 (91 days).
		///
		/// The signer implementation is then free to issue a certificate with any lifetime *shorter* than MaxExpirationSeconds, but no shorter than 3600 seconds (1 hour).  This constraint is enforced by kube-apiserver. `kubernetes.io` signers will never issue certificates with a lifetime longer than 24 hours.
		///
		public var maxExpirationSeconds: Int32?
		///
		/// nodeName is the name of the node the pod is assigned to.
		///
		public var nodeName: String
		///
		/// nodeUID is the UID of the node the pod is assigned to.
		///
		public var nodeUID: String
		///
		/// pkixPublicKey is the PKIX-serialized public key the signer will issue the certificate to.
		///
		/// The key must be one of RSA3072, RSA4096, ECDSAP256, ECDSAP384, ECDSAP521, or ED25519. Note that this list may be expanded in the future.
		///
		/// Signer implementations do not need to support all key types supported by kube-apiserver and kubelet.  If a signer does not support the key type used for a given PodCertificateRequest, it must deny the request by setting a status.conditions entry with a type of "Denied" and a reason of "UnsupportedKeyType". It may also suggest a key type that it does support in the message field.
		///
		public var pkixPublicKey: String
		///
		/// podName is the name of the pod into which the certificate will be mounted.
		///
		public var podName: String
		///
		/// podUID is the UID of the pod into which the certificate will be mounted.
		///
		public var podUID: String
		///
		/// proofOfPossession proves that the requesting kubelet holds the private key corresponding to pkixPublicKey.
		///
		/// It is contructed by signing the ASCII bytes of the pod's UID using `pkixPublicKey`.
		///
		/// kube-apiserver validates the proof of possession during creation of the PodCertificateRequest.
		///
		/// If the key is an RSA key, then the signature is over the ASCII bytes of the pod UID, using RSASSA-PSS from RFC 8017 (as implemented by the golang function crypto/rsa.SignPSS with nil options).
		///
		/// If the key is an ECDSA key, then the signature is as described by [SEC 1, Version 2.0](https://www.secg.org/sec1-v2.pdf) (as implemented by the golang library function crypto/ecdsa.SignASN1)
		///
		/// If the key is an ED25519 key, the the signature is as described by the [ED25519 Specification](https://ed25519.cr.yp.to/) (as implemented by the golang library crypto/ed25519.Sign).
		///
		public var proofOfPossession: String
		///
		/// serviceAccountName is the name of the service account the pod is running as.
		///
		public var serviceAccountName: String
		///
		/// serviceAccountUID is the UID of the service account the pod is running as.
		///
		public var serviceAccountUID: String
		///
		/// signerName indicates the requested signer.
		///
		/// All signer names beginning with `kubernetes.io` are reserved for use by the Kubernetes project.  There is currently one well-known signer documented by the Kubernetes project, `kubernetes.io/kube-apiserver-client-pod`, which will issue client certificates understood by kube-apiserver.  It is currently unimplemented.
		///
		public var signerName: String
		///
		/// Default memberwise initializer
		///
		public init(
			maxExpirationSeconds: Int32? = nil,
			nodeName: String,
			nodeUID: String,
			pkixPublicKey: String,
			podName: String,
			podUID: String,
			proofOfPossession: String,
			serviceAccountName: String,
			serviceAccountUID: String,
			signerName: String
		) {
			self.maxExpirationSeconds = maxExpirationSeconds
			self.nodeName = nodeName
			self.nodeUID = nodeUID
			self.pkixPublicKey = pkixPublicKey
			self.podName = podName
			self.podUID = podUID
			self.proofOfPossession = proofOfPossession
			self.serviceAccountName = serviceAccountName
			self.serviceAccountUID = serviceAccountUID
			self.signerName = signerName
		}
	}
}

///
/// Codable conformance
///
public extension certificates.v1alpha1.PodCertificateRequestSpec {

	private enum CodingKeys: String, CodingKey {

		case maxExpirationSeconds = "maxExpirationSeconds"
		case nodeName = "nodeName"
		case nodeUID = "nodeUID"
		case pkixPublicKey = "pkixPublicKey"
		case podName = "podName"
		case podUID = "podUID"
		case proofOfPossession = "proofOfPossession"
		case serviceAccountName = "serviceAccountName"
		case serviceAccountUID = "serviceAccountUID"
		case signerName = "signerName"
	}

	init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		self.maxExpirationSeconds = try container.decodeIfPresent(Int32.self, forKey: .maxExpirationSeconds)
		self.nodeName = try container.decode(String.self, forKey: .nodeName)
		self.nodeUID = try container.decode(String.self, forKey: .nodeUID)
		self.pkixPublicKey = try container.decode(String.self, forKey: .pkixPublicKey)
		self.podName = try container.decode(String.self, forKey: .podName)
		self.podUID = try container.decode(String.self, forKey: .podUID)
		self.proofOfPossession = try container.decode(String.self, forKey: .proofOfPossession)
		self.serviceAccountName = try container.decode(String.self, forKey: .serviceAccountName)
		self.serviceAccountUID = try container.decode(String.self, forKey: .serviceAccountUID)
		self.signerName = try container.decode(String.self, forKey: .signerName)
	}

	func encode(to encoder: Encoder) throws {
		var encodingContainer = encoder.container(keyedBy: CodingKeys.self)

		try encodingContainer.encode(maxExpirationSeconds, forKey: .maxExpirationSeconds)
		try encodingContainer.encode(nodeName, forKey: .nodeName)
		try encodingContainer.encode(nodeUID, forKey: .nodeUID)
		try encodingContainer.encode(pkixPublicKey, forKey: .pkixPublicKey)
		try encodingContainer.encode(podName, forKey: .podName)
		try encodingContainer.encode(podUID, forKey: .podUID)
		try encodingContainer.encode(proofOfPossession, forKey: .proofOfPossession)
		try encodingContainer.encode(serviceAccountName, forKey: .serviceAccountName)
		try encodingContainer.encode(serviceAccountUID, forKey: .serviceAccountUID)
		try encodingContainer.encode(signerName, forKey: .signerName)
	}
}
