//
// Copyright 2020 Iskandar Abudiab (iabudiab.dev)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

///
/// Generated by Swiftkube:ModelGen
/// Kubernetes v1.18.9
///

import Foundation

///
/// GroupVersionKind unambiguously identifies a kind.
///
public enum GroupVersionKind: String, CaseIterable {

	case coreV1Binding = "v1/Binding"
	case coreV1Componentstatus = "v1/ComponentStatus"
	case coreV1Configmap = "v1/ConfigMap"
	case coreV1Endpoints = "v1/Endpoints"
	case coreV1Event = "v1/Event"
	case coreV1Limitrange = "v1/LimitRange"
	case coreV1Namespace = "v1/Namespace"
	case coreV1Node = "v1/Node"
	case coreV1Persistentvolume = "v1/PersistentVolume"
	case coreV1Persistentvolumeclaim = "v1/PersistentVolumeClaim"
	case coreV1Pod = "v1/Pod"
	case coreV1Podtemplate = "v1/PodTemplate"
	case coreV1Replicationcontroller = "v1/ReplicationController"
	case coreV1Resourcequota = "v1/ResourceQuota"
	case coreV1Secret = "v1/Secret"
	case coreV1Service = "v1/Service"
	case coreV1Serviceaccount = "v1/ServiceAccount"
	case admissionregistrationV1Mutatingwebhookconfiguration = "admissionregistration.k8s.io/v1/MutatingWebhookConfiguration"
	case admissionregistrationV1Validatingwebhookconfiguration = "admissionregistration.k8s.io/v1/ValidatingWebhookConfiguration"
	case admissionregistrationV1Beta1Mutatingwebhookconfiguration = "admissionregistration.k8s.io/v1beta1/MutatingWebhookConfiguration"
	case admissionregistrationV1Beta1Validatingwebhookconfiguration = "admissionregistration.k8s.io/v1beta1/ValidatingWebhookConfiguration"
	case apiextensionsV1Customresourcedefinition = "apiextensions.k8s.io/v1/CustomResourceDefinition"
	case apiextensionsV1Beta1Customresourcedefinition = "apiextensions.k8s.io/v1beta1/CustomResourceDefinition"
	case apiregistrationV1Apiservice = "apiregistration.k8s.io/v1/APIService"
	case apiregistrationV1Beta1Apiservice = "apiregistration.k8s.io/v1beta1/APIService"
	case appsV1Controllerrevision = "apps/v1/ControllerRevision"
	case appsV1Daemonset = "apps/v1/DaemonSet"
	case appsV1Deployment = "apps/v1/Deployment"
	case appsV1Replicaset = "apps/v1/ReplicaSet"
	case appsV1Statefulset = "apps/v1/StatefulSet"
	case authenticationV1Tokenreview = "authentication.k8s.io/v1/TokenReview"
	case authenticationV1Beta1Tokenreview = "authentication.k8s.io/v1beta1/TokenReview"
	case authorizationV1Localsubjectaccessreview = "authorization.k8s.io/v1/LocalSubjectAccessReview"
	case authorizationV1Selfsubjectaccessreview = "authorization.k8s.io/v1/SelfSubjectAccessReview"
	case authorizationV1Selfsubjectrulesreview = "authorization.k8s.io/v1/SelfSubjectRulesReview"
	case authorizationV1Subjectaccessreview = "authorization.k8s.io/v1/SubjectAccessReview"
	case authorizationV1Beta1Localsubjectaccessreview = "authorization.k8s.io/v1beta1/LocalSubjectAccessReview"
	case authorizationV1Beta1Selfsubjectaccessreview = "authorization.k8s.io/v1beta1/SelfSubjectAccessReview"
	case authorizationV1Beta1Selfsubjectrulesreview = "authorization.k8s.io/v1beta1/SelfSubjectRulesReview"
	case authorizationV1Beta1Subjectaccessreview = "authorization.k8s.io/v1beta1/SubjectAccessReview"
	case autoscalingV1Horizontalpodautoscaler = "autoscaling/v1/HorizontalPodAutoscaler"
	case autoscalingV2Beta2Horizontalpodautoscaler = "autoscaling/v2beta2/HorizontalPodAutoscaler"
	case autoscalingV2Beta1Horizontalpodautoscaler = "autoscaling/v2beta1/HorizontalPodAutoscaler"
	case batchV1Job = "batch/v1/Job"
	case batchV1Beta1Cronjob = "batch/v1beta1/CronJob"
	case batchV2Alpha1Cronjob = "batch/v2alpha1/CronJob"
	case certificatesV1Beta1Certificatesigningrequest = "certificates.k8s.io/v1beta1/CertificateSigningRequest"
	case coordinationV1Lease = "coordination.k8s.io/v1/Lease"
	case coordinationV1Beta1Lease = "coordination.k8s.io/v1beta1/Lease"
	case discoveryV1Beta1Endpointslice = "discovery.k8s.io/v1beta1/EndpointSlice"
	case eventsV1Beta1Event = "events.k8s.io/v1beta1/Event"
	case extensionsV1Beta1Ingress = "extensions/v1beta1/Ingress"
	case networkingV1Networkpolicy = "networking.k8s.io/v1/NetworkPolicy"
	case networkingV1Beta1Ingress = "networking.k8s.io/v1beta1/Ingress"
	case networkingV1Beta1Ingressclass = "networking.k8s.io/v1beta1/IngressClass"
	case nodeV1Beta1Runtimeclass = "node.k8s.io/v1beta1/RuntimeClass"
	case nodeV1Alpha1Runtimeclass = "node.k8s.io/v1alpha1/RuntimeClass"
	case policyV1Beta1Poddisruptionbudget = "policy/v1beta1/PodDisruptionBudget"
	case policyV1Beta1Podsecuritypolicy = "policy/v1beta1/PodSecurityPolicy"
	case rbacV1Clusterrole = "rbac.authorization.k8s.io/v1/ClusterRole"
	case rbacV1Clusterrolebinding = "rbac.authorization.k8s.io/v1/ClusterRoleBinding"
	case rbacV1Role = "rbac.authorization.k8s.io/v1/Role"
	case rbacV1Rolebinding = "rbac.authorization.k8s.io/v1/RoleBinding"
	case rbacV1Beta1Clusterrole = "rbac.authorization.k8s.io/v1beta1/ClusterRole"
	case rbacV1Beta1Clusterrolebinding = "rbac.authorization.k8s.io/v1beta1/ClusterRoleBinding"
	case rbacV1Beta1Role = "rbac.authorization.k8s.io/v1beta1/Role"
	case rbacV1Beta1Rolebinding = "rbac.authorization.k8s.io/v1beta1/RoleBinding"
	case rbacV1Alpha1Clusterrole = "rbac.authorization.k8s.io/v1alpha1/ClusterRole"
	case rbacV1Alpha1Clusterrolebinding = "rbac.authorization.k8s.io/v1alpha1/ClusterRoleBinding"
	case rbacV1Alpha1Role = "rbac.authorization.k8s.io/v1alpha1/Role"
	case rbacV1Alpha1Rolebinding = "rbac.authorization.k8s.io/v1alpha1/RoleBinding"
	case schedulingV1Priorityclass = "scheduling.k8s.io/v1/PriorityClass"
	case schedulingV1Beta1Priorityclass = "scheduling.k8s.io/v1beta1/PriorityClass"
	case schedulingV1Alpha1Priorityclass = "scheduling.k8s.io/v1alpha1/PriorityClass"
	case storageV1Csidriver = "storage.k8s.io/v1/CSIDriver"
	case storageV1Csinode = "storage.k8s.io/v1/CSINode"
	case storageV1Storageclass = "storage.k8s.io/v1/StorageClass"
	case storageV1Volumeattachment = "storage.k8s.io/v1/VolumeAttachment"
	case storageV1Beta1Csidriver = "storage.k8s.io/v1beta1/CSIDriver"
	case storageV1Beta1Csinode = "storage.k8s.io/v1beta1/CSINode"
	case storageV1Beta1Storageclass = "storage.k8s.io/v1beta1/StorageClass"
	case storageV1Beta1Volumeattachment = "storage.k8s.io/v1beta1/VolumeAttachment"
	case storageV1Alpha1Volumeattachment = "storage.k8s.io/v1alpha1/VolumeAttachment"

	/// The group of this GroupVersionKind
	public var group: String {
		switch self {

		case .coreV1Binding:
			return "core"
		case .coreV1Componentstatus:
			return "core"
		case .coreV1Configmap:
			return "core"
		case .coreV1Endpoints:
			return "core"
		case .coreV1Event:
			return "core"
		case .coreV1Limitrange:
			return "core"
		case .coreV1Namespace:
			return "core"
		case .coreV1Node:
			return "core"
		case .coreV1Persistentvolume:
			return "core"
		case .coreV1Persistentvolumeclaim:
			return "core"
		case .coreV1Pod:
			return "core"
		case .coreV1Podtemplate:
			return "core"
		case .coreV1Replicationcontroller:
			return "core"
		case .coreV1Resourcequota:
			return "core"
		case .coreV1Secret:
			return "core"
		case .coreV1Service:
			return "core"
		case .coreV1Serviceaccount:
			return "core"
		case .admissionregistrationV1Mutatingwebhookconfiguration:
			return "admissionregistration.k8s.io"
		case .admissionregistrationV1Validatingwebhookconfiguration:
			return "admissionregistration.k8s.io"
		case .admissionregistrationV1Beta1Mutatingwebhookconfiguration:
			return "admissionregistration.k8s.io"
		case .admissionregistrationV1Beta1Validatingwebhookconfiguration:
			return "admissionregistration.k8s.io"
		case .apiextensionsV1Customresourcedefinition:
			return "apiextensions.k8s.io"
		case .apiextensionsV1Beta1Customresourcedefinition:
			return "apiextensions.k8s.io"
		case .apiregistrationV1Apiservice:
			return "apiregistration.k8s.io"
		case .apiregistrationV1Beta1Apiservice:
			return "apiregistration.k8s.io"
		case .appsV1Controllerrevision:
			return "apps"
		case .appsV1Daemonset:
			return "apps"
		case .appsV1Deployment:
			return "apps"
		case .appsV1Replicaset:
			return "apps"
		case .appsV1Statefulset:
			return "apps"
		case .authenticationV1Tokenreview:
			return "authentication.k8s.io"
		case .authenticationV1Beta1Tokenreview:
			return "authentication.k8s.io"
		case .authorizationV1Localsubjectaccessreview:
			return "authorization.k8s.io"
		case .authorizationV1Selfsubjectaccessreview:
			return "authorization.k8s.io"
		case .authorizationV1Selfsubjectrulesreview:
			return "authorization.k8s.io"
		case .authorizationV1Subjectaccessreview:
			return "authorization.k8s.io"
		case .authorizationV1Beta1Localsubjectaccessreview:
			return "authorization.k8s.io"
		case .authorizationV1Beta1Selfsubjectaccessreview:
			return "authorization.k8s.io"
		case .authorizationV1Beta1Selfsubjectrulesreview:
			return "authorization.k8s.io"
		case .authorizationV1Beta1Subjectaccessreview:
			return "authorization.k8s.io"
		case .autoscalingV1Horizontalpodautoscaler:
			return "autoscaling"
		case .autoscalingV2Beta2Horizontalpodautoscaler:
			return "autoscaling"
		case .autoscalingV2Beta1Horizontalpodautoscaler:
			return "autoscaling"
		case .batchV1Job:
			return "batch"
		case .batchV1Beta1Cronjob:
			return "batch"
		case .batchV2Alpha1Cronjob:
			return "batch"
		case .certificatesV1Beta1Certificatesigningrequest:
			return "certificates.k8s.io"
		case .coordinationV1Lease:
			return "coordination.k8s.io"
		case .coordinationV1Beta1Lease:
			return "coordination.k8s.io"
		case .discoveryV1Beta1Endpointslice:
			return "discovery.k8s.io"
		case .eventsV1Beta1Event:
			return "events.k8s.io"
		case .extensionsV1Beta1Ingress:
			return "extensions"
		case .networkingV1Networkpolicy:
			return "networking.k8s.io"
		case .networkingV1Beta1Ingress:
			return "networking.k8s.io"
		case .networkingV1Beta1Ingressclass:
			return "networking.k8s.io"
		case .nodeV1Beta1Runtimeclass:
			return "node.k8s.io"
		case .nodeV1Alpha1Runtimeclass:
			return "node.k8s.io"
		case .policyV1Beta1Poddisruptionbudget:
			return "policy"
		case .policyV1Beta1Podsecuritypolicy:
			return "policy"
		case .rbacV1Clusterrole:
			return "rbac.authorization.k8s.io"
		case .rbacV1Clusterrolebinding:
			return "rbac.authorization.k8s.io"
		case .rbacV1Role:
			return "rbac.authorization.k8s.io"
		case .rbacV1Rolebinding:
			return "rbac.authorization.k8s.io"
		case .rbacV1Beta1Clusterrole:
			return "rbac.authorization.k8s.io"
		case .rbacV1Beta1Clusterrolebinding:
			return "rbac.authorization.k8s.io"
		case .rbacV1Beta1Role:
			return "rbac.authorization.k8s.io"
		case .rbacV1Beta1Rolebinding:
			return "rbac.authorization.k8s.io"
		case .rbacV1Alpha1Clusterrole:
			return "rbac.authorization.k8s.io"
		case .rbacV1Alpha1Clusterrolebinding:
			return "rbac.authorization.k8s.io"
		case .rbacV1Alpha1Role:
			return "rbac.authorization.k8s.io"
		case .rbacV1Alpha1Rolebinding:
			return "rbac.authorization.k8s.io"
		case .schedulingV1Priorityclass:
			return "scheduling.k8s.io"
		case .schedulingV1Beta1Priorityclass:
			return "scheduling.k8s.io"
		case .schedulingV1Alpha1Priorityclass:
			return "scheduling.k8s.io"
		case .storageV1Csidriver:
			return "storage.k8s.io"
		case .storageV1Csinode:
			return "storage.k8s.io"
		case .storageV1Storageclass:
			return "storage.k8s.io"
		case .storageV1Volumeattachment:
			return "storage.k8s.io"
		case .storageV1Beta1Csidriver:
			return "storage.k8s.io"
		case .storageV1Beta1Csinode:
			return "storage.k8s.io"
		case .storageV1Beta1Storageclass:
			return "storage.k8s.io"
		case .storageV1Beta1Volumeattachment:
			return "storage.k8s.io"
		case .storageV1Alpha1Volumeattachment:
			return "storage.k8s.io"
		}
	}

	/// The version of this GroupVersionKind
	public var version: String {
		switch self {

		case .coreV1Binding:
			return "v1"
		case .coreV1Componentstatus:
			return "v1"
		case .coreV1Configmap:
			return "v1"
		case .coreV1Endpoints:
			return "v1"
		case .coreV1Event:
			return "v1"
		case .coreV1Limitrange:
			return "v1"
		case .coreV1Namespace:
			return "v1"
		case .coreV1Node:
			return "v1"
		case .coreV1Persistentvolume:
			return "v1"
		case .coreV1Persistentvolumeclaim:
			return "v1"
		case .coreV1Pod:
			return "v1"
		case .coreV1Podtemplate:
			return "v1"
		case .coreV1Replicationcontroller:
			return "v1"
		case .coreV1Resourcequota:
			return "v1"
		case .coreV1Secret:
			return "v1"
		case .coreV1Service:
			return "v1"
		case .coreV1Serviceaccount:
			return "v1"
		case .admissionregistrationV1Mutatingwebhookconfiguration:
			return "v1"
		case .admissionregistrationV1Validatingwebhookconfiguration:
			return "v1"
		case .admissionregistrationV1Beta1Mutatingwebhookconfiguration:
			return "v1beta1"
		case .admissionregistrationV1Beta1Validatingwebhookconfiguration:
			return "v1beta1"
		case .apiextensionsV1Customresourcedefinition:
			return "v1"
		case .apiextensionsV1Beta1Customresourcedefinition:
			return "v1beta1"
		case .apiregistrationV1Apiservice:
			return "v1"
		case .apiregistrationV1Beta1Apiservice:
			return "v1beta1"
		case .appsV1Controllerrevision:
			return "v1"
		case .appsV1Daemonset:
			return "v1"
		case .appsV1Deployment:
			return "v1"
		case .appsV1Replicaset:
			return "v1"
		case .appsV1Statefulset:
			return "v1"
		case .authenticationV1Tokenreview:
			return "v1"
		case .authenticationV1Beta1Tokenreview:
			return "v1beta1"
		case .authorizationV1Localsubjectaccessreview:
			return "v1"
		case .authorizationV1Selfsubjectaccessreview:
			return "v1"
		case .authorizationV1Selfsubjectrulesreview:
			return "v1"
		case .authorizationV1Subjectaccessreview:
			return "v1"
		case .authorizationV1Beta1Localsubjectaccessreview:
			return "v1beta1"
		case .authorizationV1Beta1Selfsubjectaccessreview:
			return "v1beta1"
		case .authorizationV1Beta1Selfsubjectrulesreview:
			return "v1beta1"
		case .authorizationV1Beta1Subjectaccessreview:
			return "v1beta1"
		case .autoscalingV1Horizontalpodautoscaler:
			return "v1"
		case .autoscalingV2Beta2Horizontalpodautoscaler:
			return "v2beta2"
		case .autoscalingV2Beta1Horizontalpodautoscaler:
			return "v2beta1"
		case .batchV1Job:
			return "v1"
		case .batchV1Beta1Cronjob:
			return "v1beta1"
		case .batchV2Alpha1Cronjob:
			return "v2alpha1"
		case .certificatesV1Beta1Certificatesigningrequest:
			return "v1beta1"
		case .coordinationV1Lease:
			return "v1"
		case .coordinationV1Beta1Lease:
			return "v1beta1"
		case .discoveryV1Beta1Endpointslice:
			return "v1beta1"
		case .eventsV1Beta1Event:
			return "v1beta1"
		case .extensionsV1Beta1Ingress:
			return "v1beta1"
		case .networkingV1Networkpolicy:
			return "v1"
		case .networkingV1Beta1Ingress:
			return "v1beta1"
		case .networkingV1Beta1Ingressclass:
			return "v1beta1"
		case .nodeV1Beta1Runtimeclass:
			return "v1beta1"
		case .nodeV1Alpha1Runtimeclass:
			return "v1alpha1"
		case .policyV1Beta1Poddisruptionbudget:
			return "v1beta1"
		case .policyV1Beta1Podsecuritypolicy:
			return "v1beta1"
		case .rbacV1Clusterrole:
			return "v1"
		case .rbacV1Clusterrolebinding:
			return "v1"
		case .rbacV1Role:
			return "v1"
		case .rbacV1Rolebinding:
			return "v1"
		case .rbacV1Beta1Clusterrole:
			return "v1beta1"
		case .rbacV1Beta1Clusterrolebinding:
			return "v1beta1"
		case .rbacV1Beta1Role:
			return "v1beta1"
		case .rbacV1Beta1Rolebinding:
			return "v1beta1"
		case .rbacV1Alpha1Clusterrole:
			return "v1alpha1"
		case .rbacV1Alpha1Clusterrolebinding:
			return "v1alpha1"
		case .rbacV1Alpha1Role:
			return "v1alpha1"
		case .rbacV1Alpha1Rolebinding:
			return "v1alpha1"
		case .schedulingV1Priorityclass:
			return "v1"
		case .schedulingV1Beta1Priorityclass:
			return "v1beta1"
		case .schedulingV1Alpha1Priorityclass:
			return "v1alpha1"
		case .storageV1Csidriver:
			return "v1"
		case .storageV1Csinode:
			return "v1"
		case .storageV1Storageclass:
			return "v1"
		case .storageV1Volumeattachment:
			return "v1"
		case .storageV1Beta1Csidriver:
			return "v1beta1"
		case .storageV1Beta1Csinode:
			return "v1beta1"
		case .storageV1Beta1Storageclass:
			return "v1beta1"
		case .storageV1Beta1Volumeattachment:
			return "v1beta1"
		case .storageV1Alpha1Volumeattachment:
			return "v1alpha1"
		}
	}

	/// The kind of this GroupVersionKind
	public var kind: String {
		switch self {

		case .coreV1Binding:
			return "Binding"
		case .coreV1Componentstatus:
			return "ComponentStatus"
		case .coreV1Configmap:
			return "ConfigMap"
		case .coreV1Endpoints:
			return "Endpoints"
		case .coreV1Event:
			return "Event"
		case .coreV1Limitrange:
			return "LimitRange"
		case .coreV1Namespace:
			return "Namespace"
		case .coreV1Node:
			return "Node"
		case .coreV1Persistentvolume:
			return "PersistentVolume"
		case .coreV1Persistentvolumeclaim:
			return "PersistentVolumeClaim"
		case .coreV1Pod:
			return "Pod"
		case .coreV1Podtemplate:
			return "PodTemplate"
		case .coreV1Replicationcontroller:
			return "ReplicationController"
		case .coreV1Resourcequota:
			return "ResourceQuota"
		case .coreV1Secret:
			return "Secret"
		case .coreV1Service:
			return "Service"
		case .coreV1Serviceaccount:
			return "ServiceAccount"
		case .admissionregistrationV1Mutatingwebhookconfiguration:
			return "MutatingWebhookConfiguration"
		case .admissionregistrationV1Validatingwebhookconfiguration:
			return "ValidatingWebhookConfiguration"
		case .admissionregistrationV1Beta1Mutatingwebhookconfiguration:
			return "MutatingWebhookConfiguration"
		case .admissionregistrationV1Beta1Validatingwebhookconfiguration:
			return "ValidatingWebhookConfiguration"
		case .apiextensionsV1Customresourcedefinition:
			return "CustomResourceDefinition"
		case .apiextensionsV1Beta1Customresourcedefinition:
			return "CustomResourceDefinition"
		case .apiregistrationV1Apiservice:
			return "APIService"
		case .apiregistrationV1Beta1Apiservice:
			return "APIService"
		case .appsV1Controllerrevision:
			return "ControllerRevision"
		case .appsV1Daemonset:
			return "DaemonSet"
		case .appsV1Deployment:
			return "Deployment"
		case .appsV1Replicaset:
			return "ReplicaSet"
		case .appsV1Statefulset:
			return "StatefulSet"
		case .authenticationV1Tokenreview:
			return "TokenReview"
		case .authenticationV1Beta1Tokenreview:
			return "TokenReview"
		case .authorizationV1Localsubjectaccessreview:
			return "LocalSubjectAccessReview"
		case .authorizationV1Selfsubjectaccessreview:
			return "SelfSubjectAccessReview"
		case .authorizationV1Selfsubjectrulesreview:
			return "SelfSubjectRulesReview"
		case .authorizationV1Subjectaccessreview:
			return "SubjectAccessReview"
		case .authorizationV1Beta1Localsubjectaccessreview:
			return "LocalSubjectAccessReview"
		case .authorizationV1Beta1Selfsubjectaccessreview:
			return "SelfSubjectAccessReview"
		case .authorizationV1Beta1Selfsubjectrulesreview:
			return "SelfSubjectRulesReview"
		case .authorizationV1Beta1Subjectaccessreview:
			return "SubjectAccessReview"
		case .autoscalingV1Horizontalpodautoscaler:
			return "HorizontalPodAutoscaler"
		case .autoscalingV2Beta2Horizontalpodautoscaler:
			return "HorizontalPodAutoscaler"
		case .autoscalingV2Beta1Horizontalpodautoscaler:
			return "HorizontalPodAutoscaler"
		case .batchV1Job:
			return "Job"
		case .batchV1Beta1Cronjob:
			return "CronJob"
		case .batchV2Alpha1Cronjob:
			return "CronJob"
		case .certificatesV1Beta1Certificatesigningrequest:
			return "CertificateSigningRequest"
		case .coordinationV1Lease:
			return "Lease"
		case .coordinationV1Beta1Lease:
			return "Lease"
		case .discoveryV1Beta1Endpointslice:
			return "EndpointSlice"
		case .eventsV1Beta1Event:
			return "Event"
		case .extensionsV1Beta1Ingress:
			return "Ingress"
		case .networkingV1Networkpolicy:
			return "NetworkPolicy"
		case .networkingV1Beta1Ingress:
			return "Ingress"
		case .networkingV1Beta1Ingressclass:
			return "IngressClass"
		case .nodeV1Beta1Runtimeclass:
			return "RuntimeClass"
		case .nodeV1Alpha1Runtimeclass:
			return "RuntimeClass"
		case .policyV1Beta1Poddisruptionbudget:
			return "PodDisruptionBudget"
		case .policyV1Beta1Podsecuritypolicy:
			return "PodSecurityPolicy"
		case .rbacV1Clusterrole:
			return "ClusterRole"
		case .rbacV1Clusterrolebinding:
			return "ClusterRoleBinding"
		case .rbacV1Role:
			return "Role"
		case .rbacV1Rolebinding:
			return "RoleBinding"
		case .rbacV1Beta1Clusterrole:
			return "ClusterRole"
		case .rbacV1Beta1Clusterrolebinding:
			return "ClusterRoleBinding"
		case .rbacV1Beta1Role:
			return "Role"
		case .rbacV1Beta1Rolebinding:
			return "RoleBinding"
		case .rbacV1Alpha1Clusterrole:
			return "ClusterRole"
		case .rbacV1Alpha1Clusterrolebinding:
			return "ClusterRoleBinding"
		case .rbacV1Alpha1Role:
			return "Role"
		case .rbacV1Alpha1Rolebinding:
			return "RoleBinding"
		case .schedulingV1Priorityclass:
			return "PriorityClass"
		case .schedulingV1Beta1Priorityclass:
			return "PriorityClass"
		case .schedulingV1Alpha1Priorityclass:
			return "PriorityClass"
		case .storageV1Csidriver:
			return "CSIDriver"
		case .storageV1Csinode:
			return "CSINode"
		case .storageV1Storageclass:
			return "StorageClass"
		case .storageV1Volumeattachment:
			return "VolumeAttachment"
		case .storageV1Beta1Csidriver:
			return "CSIDriver"
		case .storageV1Beta1Csinode:
			return "CSINode"
		case .storageV1Beta1Storageclass:
			return "StorageClass"
		case .storageV1Beta1Volumeattachment:
			return "VolumeAttachment"
		case .storageV1Alpha1Volumeattachment:
			return "VolumeAttachment"
		}
	}

	/// The API Version of this GroupVersionKind.
	public var apiVersion: String {
		if group == "core" {
			return version
		} else {
			return "\(group)/\(version)"
		}
	}

	/// The kind of this GroupVersionKind
	public var pluralName: String {
		switch self {

		case .coreV1Binding:
			return "bindings"
		case .coreV1Componentstatus:
			return "componentstatuses"
		case .coreV1Configmap:
			return "configmaps"
		case .coreV1Endpoints:
			return "endpoints"
		case .coreV1Event:
			return "events"
		case .coreV1Limitrange:
			return "limitranges"
		case .coreV1Namespace:
			return "namespaces"
		case .coreV1Node:
			return "nodes"
		case .coreV1Persistentvolume:
			return "persistentvolumes"
		case .coreV1Persistentvolumeclaim:
			return "persistentvolumeclaims"
		case .coreV1Pod:
			return "pods"
		case .coreV1Podtemplate:
			return "podtemplates"
		case .coreV1Replicationcontroller:
			return "replicationcontrollers"
		case .coreV1Resourcequota:
			return "resourcequotas"
		case .coreV1Secret:
			return "secrets"
		case .coreV1Service:
			return "services"
		case .coreV1Serviceaccount:
			return "serviceaccounts"
		case .admissionregistrationV1Mutatingwebhookconfiguration:
			return "mutatingwebhookconfigurations"
		case .admissionregistrationV1Validatingwebhookconfiguration:
			return "validatingwebhookconfigurations"
		case .admissionregistrationV1Beta1Mutatingwebhookconfiguration:
			return "mutatingwebhookconfigurations"
		case .admissionregistrationV1Beta1Validatingwebhookconfiguration:
			return "validatingwebhookconfigurations"
		case .apiextensionsV1Customresourcedefinition:
			return "customresourcedefinitions"
		case .apiextensionsV1Beta1Customresourcedefinition:
			return "customresourcedefinitions"
		case .apiregistrationV1Apiservice:
			return "apiservices"
		case .apiregistrationV1Beta1Apiservice:
			return "apiservices"
		case .appsV1Controllerrevision:
			return "controllerrevisions"
		case .appsV1Daemonset:
			return "daemonsets"
		case .appsV1Deployment:
			return "deployments"
		case .appsV1Replicaset:
			return "replicasets"
		case .appsV1Statefulset:
			return "statefulsets"
		case .authenticationV1Tokenreview:
			return "tokenreviews"
		case .authenticationV1Beta1Tokenreview:
			return "tokenreviews"
		case .authorizationV1Localsubjectaccessreview:
			return "localsubjectaccessreviews"
		case .authorizationV1Selfsubjectaccessreview:
			return "selfsubjectaccessreviews"
		case .authorizationV1Selfsubjectrulesreview:
			return "selfsubjectrulesreviews"
		case .authorizationV1Subjectaccessreview:
			return "subjectaccessreviews"
		case .authorizationV1Beta1Localsubjectaccessreview:
			return "localsubjectaccessreviews"
		case .authorizationV1Beta1Selfsubjectaccessreview:
			return "selfsubjectaccessreviews"
		case .authorizationV1Beta1Selfsubjectrulesreview:
			return "selfsubjectrulesreviews"
		case .authorizationV1Beta1Subjectaccessreview:
			return "subjectaccessreviews"
		case .autoscalingV1Horizontalpodautoscaler:
			return "horizontalpodautoscalers"
		case .autoscalingV2Beta2Horizontalpodautoscaler:
			return "horizontalpodautoscalers"
		case .autoscalingV2Beta1Horizontalpodautoscaler:
			return "horizontalpodautoscalers"
		case .batchV1Job:
			return "jobs"
		case .batchV1Beta1Cronjob:
			return "cronjobs"
		case .batchV2Alpha1Cronjob:
			return "cronjobs"
		case .certificatesV1Beta1Certificatesigningrequest:
			return "certificatesigningrequests"
		case .coordinationV1Lease:
			return "leases"
		case .coordinationV1Beta1Lease:
			return "leases"
		case .discoveryV1Beta1Endpointslice:
			return "endpointslices"
		case .eventsV1Beta1Event:
			return "events"
		case .extensionsV1Beta1Ingress:
			return "ingresses"
		case .networkingV1Networkpolicy:
			return "networkpolicies"
		case .networkingV1Beta1Ingress:
			return "ingresses"
		case .networkingV1Beta1Ingressclass:
			return "ingressclasses"
		case .nodeV1Beta1Runtimeclass:
			return "runtimeclasses"
		case .nodeV1Alpha1Runtimeclass:
			return "runtimeclasses"
		case .policyV1Beta1Poddisruptionbudget:
			return "poddisruptionbudgets"
		case .policyV1Beta1Podsecuritypolicy:
			return "podsecuritypolicies"
		case .rbacV1Clusterrole:
			return "clusterroles"
		case .rbacV1Clusterrolebinding:
			return "clusterrolebindings"
		case .rbacV1Role:
			return "roles"
		case .rbacV1Rolebinding:
			return "rolebindings"
		case .rbacV1Beta1Clusterrole:
			return "clusterroles"
		case .rbacV1Beta1Clusterrolebinding:
			return "clusterrolebindings"
		case .rbacV1Beta1Role:
			return "roles"
		case .rbacV1Beta1Rolebinding:
			return "rolebindings"
		case .rbacV1Alpha1Clusterrole:
			return "clusterroles"
		case .rbacV1Alpha1Clusterrolebinding:
			return "clusterrolebindings"
		case .rbacV1Alpha1Role:
			return "roles"
		case .rbacV1Alpha1Rolebinding:
			return "rolebindings"
		case .schedulingV1Priorityclass:
			return "priorityclasses"
		case .schedulingV1Beta1Priorityclass:
			return "priorityclasses"
		case .schedulingV1Alpha1Priorityclass:
			return "priorityclasses"
		case .storageV1Csidriver:
			return "csidrivers"
		case .storageV1Csinode:
			return "csinodes"
		case .storageV1Storageclass:
			return "storageclasses"
		case .storageV1Volumeattachment:
			return "volumeattachments"
		case .storageV1Beta1Csidriver:
			return "csidrivers"
		case .storageV1Beta1Csinode:
			return "csinodes"
		case .storageV1Beta1Storageclass:
			return "storageclasses"
		case .storageV1Beta1Volumeattachment:
			return "volumeattachments"
		case .storageV1Alpha1Volumeattachment:
			return "volumeattachments"
		}
	}

	/// The kind of this GroupVersionKind
	public var shortName: String? {
		switch self {

		case .coreV1Binding:
			return nil
		case .coreV1Componentstatus:
			return "cs"
		case .coreV1Configmap:
			return "cm"
		case .coreV1Endpoints:
			return "ep"
		case .coreV1Event:
			return "ev"
		case .coreV1Limitrange:
			return "limits"
		case .coreV1Namespace:
			return "ns"
		case .coreV1Node:
			return "no"
		case .coreV1Persistentvolume:
			return "pv"
		case .coreV1Persistentvolumeclaim:
			return "pvc"
		case .coreV1Pod:
			return "po"
		case .coreV1Podtemplate:
			return nil
		case .coreV1Replicationcontroller:
			return "rc"
		case .coreV1Resourcequota:
			return "quota"
		case .coreV1Secret:
			return nil
		case .coreV1Service:
			return "svc"
		case .coreV1Serviceaccount:
			return "sa"
		case .admissionregistrationV1Mutatingwebhookconfiguration:
			return nil
		case .admissionregistrationV1Validatingwebhookconfiguration:
			return nil
		case .admissionregistrationV1Beta1Mutatingwebhookconfiguration:
			return nil
		case .admissionregistrationV1Beta1Validatingwebhookconfiguration:
			return nil
		case .apiextensionsV1Customresourcedefinition:
			return "crd"
		case .apiextensionsV1Beta1Customresourcedefinition:
			return "crd"
		case .apiregistrationV1Apiservice:
			return nil
		case .apiregistrationV1Beta1Apiservice:
			return nil
		case .appsV1Controllerrevision:
			return nil
		case .appsV1Daemonset:
			return "ds"
		case .appsV1Deployment:
			return "deploy"
		case .appsV1Replicaset:
			return "rs"
		case .appsV1Statefulset:
			return "sts"
		case .authenticationV1Tokenreview:
			return nil
		case .authenticationV1Beta1Tokenreview:
			return nil
		case .authorizationV1Localsubjectaccessreview:
			return nil
		case .authorizationV1Selfsubjectaccessreview:
			return nil
		case .authorizationV1Selfsubjectrulesreview:
			return nil
		case .authorizationV1Subjectaccessreview:
			return nil
		case .authorizationV1Beta1Localsubjectaccessreview:
			return nil
		case .authorizationV1Beta1Selfsubjectaccessreview:
			return nil
		case .authorizationV1Beta1Selfsubjectrulesreview:
			return nil
		case .authorizationV1Beta1Subjectaccessreview:
			return nil
		case .autoscalingV1Horizontalpodautoscaler:
			return "hpa"
		case .autoscalingV2Beta2Horizontalpodautoscaler:
			return "hpa"
		case .autoscalingV2Beta1Horizontalpodautoscaler:
			return "hpa"
		case .batchV1Job:
			return nil
		case .batchV1Beta1Cronjob:
			return "cj"
		case .batchV2Alpha1Cronjob:
			return "cj"
		case .certificatesV1Beta1Certificatesigningrequest:
			return "csr"
		case .coordinationV1Lease:
			return nil
		case .coordinationV1Beta1Lease:
			return nil
		case .discoveryV1Beta1Endpointslice:
			return nil
		case .eventsV1Beta1Event:
			return "ev"
		case .extensionsV1Beta1Ingress:
			return "ing"
		case .networkingV1Networkpolicy:
			return "netpol"
		case .networkingV1Beta1Ingress:
			return "ing"
		case .networkingV1Beta1Ingressclass:
			return nil
		case .nodeV1Beta1Runtimeclass:
			return nil
		case .nodeV1Alpha1Runtimeclass:
			return nil
		case .policyV1Beta1Poddisruptionbudget:
			return "pdb"
		case .policyV1Beta1Podsecuritypolicy:
			return "psp"
		case .rbacV1Clusterrole:
			return nil
		case .rbacV1Clusterrolebinding:
			return nil
		case .rbacV1Role:
			return nil
		case .rbacV1Rolebinding:
			return nil
		case .rbacV1Beta1Clusterrole:
			return nil
		case .rbacV1Beta1Clusterrolebinding:
			return nil
		case .rbacV1Beta1Role:
			return nil
		case .rbacV1Beta1Rolebinding:
			return nil
		case .rbacV1Alpha1Clusterrole:
			return nil
		case .rbacV1Alpha1Clusterrolebinding:
			return nil
		case .rbacV1Alpha1Role:
			return nil
		case .rbacV1Alpha1Rolebinding:
			return nil
		case .schedulingV1Priorityclass:
			return "pc"
		case .schedulingV1Beta1Priorityclass:
			return "pc"
		case .schedulingV1Alpha1Priorityclass:
			return "pc"
		case .storageV1Csidriver:
			return nil
		case .storageV1Csinode:
			return nil
		case .storageV1Storageclass:
			return "sc"
		case .storageV1Volumeattachment:
			return nil
		case .storageV1Beta1Csidriver:
			return nil
		case .storageV1Beta1Csinode:
			return nil
		case .storageV1Beta1Storageclass:
			return "sc"
		case .storageV1Beta1Volumeattachment:
			return nil
		case .storageV1Alpha1Volumeattachment:
			return nil
		}
	}
}
