  ////
  //// Copyright 2020 Swiftkube Project
  ////
  //// Licensed under the Apache License, Version 2.0 (the "License");
  //// you may not use this file except in compliance with the License.
  //// You may obtain a copy of the License at
  ////
  //// http://www.apache.org/licenses/LICENSE-2.0
  ////
  //// Unless required by applicable law or agreed to in writing, software
  //// distributed under the License is distributed on an "AS IS" BASIS,
  //// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  //// See the License for the specific language governing permissions and
  //// limitations under the License.
  ////

import Foundation

public extension GroupVersionKind {
  static let coreV1Binding: GroupVersionKind = "v1/Binding"
static let coreV1ComponentStatus: GroupVersionKind = "v1/ComponentStatus"
static let coreV1ConfigMap: GroupVersionKind = "v1/ConfigMap"
static let coreV1Endpoints: GroupVersionKind = "v1/Endpoints"
static let coreV1Event: GroupVersionKind = "v1/Event"
static let coreV1LimitRange: GroupVersionKind = "v1/LimitRange"
static let coreV1Namespace: GroupVersionKind = "v1/Namespace"
static let coreV1Node: GroupVersionKind = "v1/Node"
static let coreV1PersistentVolume: GroupVersionKind = "v1/PersistentVolume"
static let coreV1PersistentVolumeClaim: GroupVersionKind = "v1/PersistentVolumeClaim"
static let coreV1Pod: GroupVersionKind = "v1/Pod"
static let coreV1PodTemplate: GroupVersionKind = "v1/PodTemplate"
static let coreV1ReplicationController: GroupVersionKind = "v1/ReplicationController"
static let coreV1ResourceQuota: GroupVersionKind = "v1/ResourceQuota"
static let coreV1Secret: GroupVersionKind = "v1/Secret"
static let coreV1Service: GroupVersionKind = "v1/Service"
static let coreV1ServiceAccount: GroupVersionKind = "v1/ServiceAccount"
static let admissionregistrationV1MutatingWebhookConfiguration: GroupVersionKind = "admissionregistration.k8s.io/v1/MutatingWebhookConfiguration"
static let admissionregistrationV1ValidatingWebhookConfiguration: GroupVersionKind = "admissionregistration.k8s.io/v1/ValidatingWebhookConfiguration"
static let admissionregistrationV1Beta1MutatingWebhookConfiguration: GroupVersionKind = "admissionregistration.k8s.io/v1beta1/MutatingWebhookConfiguration"
static let admissionregistrationV1Beta1ValidatingWebhookConfiguration: GroupVersionKind = "admissionregistration.k8s.io/v1beta1/ValidatingWebhookConfiguration"
static let apiextensionsV1CustomResourceDefinition: GroupVersionKind = "apiextensions.k8s.io/v1/CustomResourceDefinition"
static let apiextensionsV1Beta1CustomResourceDefinition: GroupVersionKind = "apiextensions.k8s.io/v1beta1/CustomResourceDefinition"
static let apiregistrationV1APIService: GroupVersionKind = "apiregistration.k8s.io/v1/APIService"
static let apiregistrationV1Beta1APIService: GroupVersionKind = "apiregistration.k8s.io/v1beta1/APIService"
static let appsV1ControllerRevision: GroupVersionKind = "apps/v1/ControllerRevision"
static let appsV1DaemonSet: GroupVersionKind = "apps/v1/DaemonSet"
static let appsV1Deployment: GroupVersionKind = "apps/v1/Deployment"
static let appsV1ReplicaSet: GroupVersionKind = "apps/v1/ReplicaSet"
static let appsV1StatefulSet: GroupVersionKind = "apps/v1/StatefulSet"
static let authenticationV1TokenRequest: GroupVersionKind = "authentication.k8s.io/v1/TokenRequest"
static let authenticationV1TokenReview: GroupVersionKind = "authentication.k8s.io/v1/TokenReview"
static let authenticationV1Beta1TokenReview: GroupVersionKind = "authentication.k8s.io/v1beta1/TokenReview"
static let authorizationV1LocalSubjectAccessReview: GroupVersionKind = "authorization.k8s.io/v1/LocalSubjectAccessReview"
static let authorizationV1SelfSubjectAccessReview: GroupVersionKind = "authorization.k8s.io/v1/SelfSubjectAccessReview"
static let authorizationV1SelfSubjectRulesReview: GroupVersionKind = "authorization.k8s.io/v1/SelfSubjectRulesReview"
static let authorizationV1SubjectAccessReview: GroupVersionKind = "authorization.k8s.io/v1/SubjectAccessReview"
static let authorizationV1Beta1LocalSubjectAccessReview: GroupVersionKind = "authorization.k8s.io/v1beta1/LocalSubjectAccessReview"
static let authorizationV1Beta1SelfSubjectAccessReview: GroupVersionKind = "authorization.k8s.io/v1beta1/SelfSubjectAccessReview"
static let authorizationV1Beta1SelfSubjectRulesReview: GroupVersionKind = "authorization.k8s.io/v1beta1/SelfSubjectRulesReview"
static let authorizationV1Beta1SubjectAccessReview: GroupVersionKind = "authorization.k8s.io/v1beta1/SubjectAccessReview"
static let autoscalingV1HorizontalPodAutoscaler: GroupVersionKind = "autoscaling/v1/HorizontalPodAutoscaler"
static let autoscalingV2Beta2HorizontalPodAutoscaler: GroupVersionKind = "autoscaling/v2beta2/HorizontalPodAutoscaler"
static let autoscalingV2Beta1HorizontalPodAutoscaler: GroupVersionKind = "autoscaling/v2beta1/HorizontalPodAutoscaler"
static let batchV1Job: GroupVersionKind = "batch/v1/Job"
static let batchV1Beta1CronJob: GroupVersionKind = "batch/v1beta1/CronJob"
static let batchV2Alpha1CronJob: GroupVersionKind = "batch/v2alpha1/CronJob"
static let certificatesV1CertificateSigningRequest: GroupVersionKind = "certificates.k8s.io/v1/CertificateSigningRequest"
static let certificatesV1Beta1CertificateSigningRequest: GroupVersionKind = "certificates.k8s.io/v1beta1/CertificateSigningRequest"
static let coordinationV1Lease: GroupVersionKind = "coordination.k8s.io/v1/Lease"
static let coordinationV1Beta1Lease: GroupVersionKind = "coordination.k8s.io/v1beta1/Lease"
static let discoveryV1Beta1EndpointSlice: GroupVersionKind = "discovery.k8s.io/v1beta1/EndpointSlice"
static let eventsV1Event: GroupVersionKind = "events.k8s.io/v1/Event"
static let eventsV1Beta1Event: GroupVersionKind = "events.k8s.io/v1beta1/Event"
static let extensionsV1Beta1Ingress: GroupVersionKind = "extensions/v1beta1/Ingress"
static let flowcontrolV1Beta1FlowSchema: GroupVersionKind = "flowcontrol.apiserver.k8s.io/v1beta1/FlowSchema"
static let flowcontrolV1Beta1PriorityLevelConfiguration: GroupVersionKind = "flowcontrol.apiserver.k8s.io/v1beta1/PriorityLevelConfiguration"
static let flowcontrolV1Alpha1FlowSchema: GroupVersionKind = "flowcontrol.apiserver.k8s.io/v1alpha1/FlowSchema"
static let flowcontrolV1Alpha1PriorityLevelConfiguration: GroupVersionKind = "flowcontrol.apiserver.k8s.io/v1alpha1/PriorityLevelConfiguration"
static let internalV1Alpha1StorageVersion: GroupVersionKind = "internal.apiserver.k8s.io/v1alpha1/StorageVersion"
static let networkingV1Ingress: GroupVersionKind = "networking.k8s.io/v1/Ingress"
static let networkingV1IngressClass: GroupVersionKind = "networking.k8s.io/v1/IngressClass"
static let networkingV1NetworkPolicy: GroupVersionKind = "networking.k8s.io/v1/NetworkPolicy"
static let networkingV1Beta1Ingress: GroupVersionKind = "networking.k8s.io/v1beta1/Ingress"
static let networkingV1Beta1IngressClass: GroupVersionKind = "networking.k8s.io/v1beta1/IngressClass"
static let nodeV1RuntimeClass: GroupVersionKind = "node.k8s.io/v1/RuntimeClass"
static let nodeV1Beta1RuntimeClass: GroupVersionKind = "node.k8s.io/v1beta1/RuntimeClass"
static let nodeV1Alpha1RuntimeClass: GroupVersionKind = "node.k8s.io/v1alpha1/RuntimeClass"
static let policyV1Beta1PodDisruptionBudget: GroupVersionKind = "policy/v1beta1/PodDisruptionBudget"
static let policyV1Beta1PodSecurityPolicy: GroupVersionKind = "policy/v1beta1/PodSecurityPolicy"
static let rbacV1ClusterRole: GroupVersionKind = "rbac.authorization.k8s.io/v1/ClusterRole"
static let rbacV1ClusterRoleBinding: GroupVersionKind = "rbac.authorization.k8s.io/v1/ClusterRoleBinding"
static let rbacV1Role: GroupVersionKind = "rbac.authorization.k8s.io/v1/Role"
static let rbacV1RoleBinding: GroupVersionKind = "rbac.authorization.k8s.io/v1/RoleBinding"
static let rbacV1Beta1ClusterRole: GroupVersionKind = "rbac.authorization.k8s.io/v1beta1/ClusterRole"
static let rbacV1Beta1ClusterRoleBinding: GroupVersionKind = "rbac.authorization.k8s.io/v1beta1/ClusterRoleBinding"
static let rbacV1Beta1Role: GroupVersionKind = "rbac.authorization.k8s.io/v1beta1/Role"
static let rbacV1Beta1RoleBinding: GroupVersionKind = "rbac.authorization.k8s.io/v1beta1/RoleBinding"
static let rbacV1Alpha1ClusterRole: GroupVersionKind = "rbac.authorization.k8s.io/v1alpha1/ClusterRole"
static let rbacV1Alpha1ClusterRoleBinding: GroupVersionKind = "rbac.authorization.k8s.io/v1alpha1/ClusterRoleBinding"
static let rbacV1Alpha1Role: GroupVersionKind = "rbac.authorization.k8s.io/v1alpha1/Role"
static let rbacV1Alpha1RoleBinding: GroupVersionKind = "rbac.authorization.k8s.io/v1alpha1/RoleBinding"
static let schedulingV1PriorityClass: GroupVersionKind = "scheduling.k8s.io/v1/PriorityClass"
static let schedulingV1Beta1PriorityClass: GroupVersionKind = "scheduling.k8s.io/v1beta1/PriorityClass"
static let schedulingV1Alpha1PriorityClass: GroupVersionKind = "scheduling.k8s.io/v1alpha1/PriorityClass"
static let storageV1CSIDriver: GroupVersionKind = "storage.k8s.io/v1/CSIDriver"
static let storageV1CSINode: GroupVersionKind = "storage.k8s.io/v1/CSINode"
static let storageV1StorageClass: GroupVersionKind = "storage.k8s.io/v1/StorageClass"
static let storageV1VolumeAttachment: GroupVersionKind = "storage.k8s.io/v1/VolumeAttachment"
static let storageV1Beta1CSIDriver: GroupVersionKind = "storage.k8s.io/v1beta1/CSIDriver"
static let storageV1Beta1CSINode: GroupVersionKind = "storage.k8s.io/v1beta1/CSINode"
static let storageV1Beta1StorageClass: GroupVersionKind = "storage.k8s.io/v1beta1/StorageClass"
static let storageV1Beta1VolumeAttachment: GroupVersionKind = "storage.k8s.io/v1beta1/VolumeAttachment"
static let storageV1Alpha1VolumeAttachment: GroupVersionKind = "storage.k8s.io/v1alpha1/VolumeAttachment"
}
