//
// Copyright 2020 Iskandar Abudiab (iabudiab.dev)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

///
/// Generated by Swiftkube:ModelGen
/// Kubernetes v1.18.9
/// autoscaling.v2beta1.PodsMetricSource
///

import Foundation

public extension autoscaling.v2beta1 {

	///
	/// PodsMetricSource indicates how to scale on a metric describing each pod in the current scale target (for example, transactions-processed-per-second). The values will be averaged together before being compared to the target value.
	///
	struct PodsMetricSource: KubernetesResource {
		///
		/// metricName is the name of the metric in question
		///
		public var metricName: String
		///
		/// selector is the string-encoded form of a standard kubernetes label selector for the given metric When set, it is passed as an additional parameter to the metrics server for more specific metrics scoping When unset, just the metricName will be used to gather metrics.
		///
		public var selector: meta.v1.LabelSelector?
		///
		/// targetAverageValue is the target value of the average of the metric across all relevant pods (as a quantity)
		///
		public var targetAverageValue: Quantity
		///
		/// Default memberwise initializer
		///
		public init(
			metricName: String,
			selector: meta.v1.LabelSelector? = nil,
			targetAverageValue: Quantity
		) {
			self.metricName = metricName
			self.selector = selector
			self.targetAverageValue = targetAverageValue
		}
	}
}

///
/// Codable conformance
///
extension autoscaling.v2beta1.PodsMetricSource {

	private enum CodingKeys: String, CodingKey {

		case metricName = "metricName"
		case selector = "selector"
		case targetAverageValue = "targetAverageValue"
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		self.metricName = try container.decode(String.self, forKey: .metricName)
		self.selector = try container.decodeIfPresent(meta.v1.LabelSelector.self, forKey: .selector)
		self.targetAverageValue = try container.decode(Quantity.self, forKey: .targetAverageValue)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)

		try container.encode(self.metricName, forKey: .metricName)
		try container.encode(self.selector, forKey: .selector)
		try container.encode(self.targetAverageValue, forKey: .targetAverageValue)
	}

}

