//
// Copyright 2020-2026 Swiftkube Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

//
// Generated by Swiftkube:ModelGen
// Kubernetes v1.35.3
// scheduling.v1alpha1.TypedLocalObjectReference
//

#if canImport(FoundationEssentials)
	import FoundationEssentials
#else
	import Foundation
#endif

// MARK: - scheduling.v1alpha1.TypedLocalObjectReference

public extension scheduling.v1alpha1 {

	///
	/// TypedLocalObjectReference allows to reference typed object inside the same namespace.
	///
	struct TypedLocalObjectReference: KubernetesResource {
		///
		/// Kind is the type of resource being referenced. It must be a path segment name.
		///
		public var kind: String
		///
		/// APIGroup is the group for the resource being referenced. If APIGroup is empty, the specified Kind must be in the core API group. For any other third-party types, setting APIGroup is required. It must be a DNS subdomain.
		///
		public var apiGroup: String?
		///
		/// Name is the name of resource being referenced. It must be a path segment name.
		///
		public var name: String
		///
		/// Default memberwise initializer
		///
		public init(
			kind: String,
			apiGroup: String? = nil,
			name: String
		) {
			self.kind = kind
			self.apiGroup = apiGroup
			self.name = name
		}
	}
}

///
/// Codable conformance
///
public extension scheduling.v1alpha1.TypedLocalObjectReference {

	private enum CodingKeys: String, CodingKey {

		case kind = "kind"
		case apiGroup = "apiGroup"
		case name = "name"
	}

	init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		self.kind = try container.decode(String.self, forKey: .kind)
		self.apiGroup = try container.decodeIfPresent(String.self, forKey: .apiGroup)
		self.name = try container.decode(String.self, forKey: .name)
	}

	func encode(to encoder: Encoder) throws {
		var encodingContainer = encoder.container(keyedBy: CodingKeys.self)

		try encodingContainer.encode(kind, forKey: .kind)
		try encodingContainer.encode(apiGroup, forKey: .apiGroup)
		try encodingContainer.encode(name, forKey: .name)
	}
}
