//
// Copyright 2020 Iskandar Abudiab (iabudiab.dev)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

///
/// Generated by Swiftkube:ModelGen
/// Kubernetes v1.18.9
/// authorization.v1.ResourceRule
///

import Foundation

public extension authorization.v1 {

	///
	/// ResourceRule is the list of actions the subject is allowed to perform on resources. The list ordering isn't significant, may contain duplicates, and possibly be incomplete.
	///
	struct ResourceRule: KubernetesResource {
		///
		/// APIGroups is the name of the APIGroup that contains the resources.  If multiple API groups are specified, any action requested against one of the enumerated resources in any API group will be allowed.  "*" means all.
		///
		public var apiGroups: [String]?
		///
		/// ResourceNames is an optional white list of names that the rule applies to.  An empty set means that everything is allowed.  "*" means all.
		///
		public var resourceNames: [String]?
		///
		/// Resources is a list of resources this rule applies to.  "*" means all in the specified apiGroups.
		///  "*/foo" represents the subresource 'foo' for all resources in the specified apiGroups.
		///
		public var resources: [String]?
		///
		/// Verb is a list of kubernetes resource API verbs, like: get, list, watch, create, update, delete, proxy.  "*" means all.
		///
		public var verbs: [String]
		///
		/// Default memberwise initializer
		///
		public init(
			apiGroups: [String]? = nil,
			resourceNames: [String]? = nil,
			resources: [String]? = nil,
			verbs: [String]
		) {
			self.apiGroups = apiGroups
			self.resourceNames = resourceNames
			self.resources = resources
			self.verbs = verbs
		}
	}
}

///
/// Codable conformance
///
extension authorization.v1.ResourceRule {

	private enum CodingKeys: String, CodingKey {
		case apiGroups = "apiGroups"
		case resourceNames = "resourceNames"
		case resources = "resources"
		case verbs = "verbs"
	}

}

