//
// Copyright 2020-2026 Swiftkube Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

//
// Generated by Swiftkube:ModelGen
// Kubernetes v1.34.6
// resource.v1beta1.DeviceCapacity
//

import Foundation

// MARK: - resource.v1beta1.DeviceCapacity

public extension resource.v1beta1 {

	///
	/// DeviceCapacity describes a quantity associated with a device.
	///
	struct DeviceCapacity: KubernetesResource {
		///
		/// RequestPolicy defines how this DeviceCapacity must be consumed when the device is allowed to be shared by multiple allocations.
		///
		/// The Device must have allowMultipleAllocations set to true in order to set a requestPolicy.
		///
		/// If unset, capacity requests are unconstrained: requests can consume any amount of capacity, as long as the total consumed across all allocations does not exceed the device's defined capacity. If request is also unset, default is the full capacity value.
		///
		public var requestPolicy: resource.v1beta1.CapacityRequestPolicy?
		///
		/// Value defines how much of a certain capacity that device has.
		///
		/// This field reflects the fixed total capacity and does not change. The consumed amount is tracked separately by scheduler and does not affect this value.
		///
		public var value: Quantity
		///
		/// Default memberwise initializer
		///
		public init(
			requestPolicy: resource.v1beta1.CapacityRequestPolicy? = nil,
			value: Quantity
		) {
			self.requestPolicy = requestPolicy
			self.value = value
		}
	}
}

///
/// Codable conformance
///
public extension resource.v1beta1.DeviceCapacity {

	private enum CodingKeys: String, CodingKey {

		case requestPolicy = "requestPolicy"
		case value = "value"
	}

	init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		self.requestPolicy = try container.decodeIfPresent(resource.v1beta1.CapacityRequestPolicy.self, forKey: .requestPolicy)
		self.value = try container.decode(Quantity.self, forKey: .value)
	}

	func encode(to encoder: Encoder) throws {
		var encodingContainer = encoder.container(keyedBy: CodingKeys.self)

		try encodingContainer.encode(requestPolicy, forKey: .requestPolicy)
		try encodingContainer.encode(value, forKey: .value)
	}
}
