//
// Copyright 2020 Swiftkube Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

///
/// Generated by Swiftkube:ModelGen
/// Kubernetes v1.33.3
/// resource.v1alpha3.CounterSet
///

import Foundation

// MARK: - resource.v1alpha3.CounterSet

public extension resource.v1alpha3 {

	///
	/// CounterSet defines a named set of counters that are available to be used by devices defined in the ResourceSlice.
	///
	/// The counters are not allocatable by themselves, but can be referenced by devices. When a device is allocated, the portion of counters it uses will no longer be available for use by other devices.
	///
	struct CounterSet: KubernetesResource {
		///
		/// Counters defines the counters that will be consumed by the device. The name of each counter must be unique in that set and must be a DNS label.
		///
		/// To ensure this uniqueness, capacities defined by the vendor must be listed without the driver name as domain prefix in their name. All others must be listed with their domain prefix.
		///
		/// The maximum number of counters is 32.
		///
		public var counters: [String: resource.v1alpha3.Counter]
		///
		/// CounterSet is the name of the set from which the counters defined will be consumed.
		///
		public var name: String
		///
		/// Default memberwise initializer
		///
		public init(
			counters: [String: resource.v1alpha3.Counter],
			name: String
		) {
			self.counters = counters
			self.name = name
		}
	}
}

///
/// Codable conformance
///
public extension resource.v1alpha3.CounterSet {

	private enum CodingKeys: String, CodingKey {

		case counters = "counters"
		case name = "name"
	}

	init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		self.counters = try container.decode([String: resource.v1alpha3.Counter].self, forKey: .counters)
		self.name = try container.decode(String.self, forKey: .name)
	}

	func encode(to encoder: Encoder) throws {
		var encodingContainer = encoder.container(keyedBy: CodingKeys.self)

		try encodingContainer.encode(counters, forKey: .counters)
		try encodingContainer.encode(name, forKey: .name)
	}
}
