//
// Copyright 2020 Swiftkube Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

///
/// Generated by Swiftkube:ModelGen
/// Kubernetes v1.33.3
/// admissionregistration.v1alpha1.MutatingAdmissionPolicyBindingSpec
///

import Foundation

// MARK: - admissionregistration.v1alpha1.MutatingAdmissionPolicyBindingSpec

public extension admissionregistration.v1alpha1 {

	///
	/// MutatingAdmissionPolicyBindingSpec is the specification of the MutatingAdmissionPolicyBinding.
	///
	struct MutatingAdmissionPolicyBindingSpec: KubernetesResource {
		///
		/// matchResources limits what resources match this binding and may be mutated by it. Note that if matchResources matches a resource, the resource must also match a policy's matchConstraints and matchConditions before the resource may be mutated. When matchResources is unset, it does not constrain resource matching, and only the policy's matchConstraints and matchConditions must match for the resource to be mutated. Additionally, matchResources.resourceRules are optional and do not constraint matching when unset. Note that this is differs from MutatingAdmissionPolicy matchConstraints, where resourceRules are required. The CREATE, UPDATE and CONNECT operations are allowed.  The DELETE operation may not be matched. '*' matches CREATE, UPDATE and CONNECT.
		///
		public var matchResources: admissionregistration.v1alpha1.MatchResources?
		///
		/// paramRef specifies the parameter resource used to configure the admission control policy. It should point to a resource of the type specified in spec.ParamKind of the bound MutatingAdmissionPolicy. If the policy specifies a ParamKind and the resource referred to by ParamRef does not exist, this binding is considered mis-configured and the FailurePolicy of the MutatingAdmissionPolicy applied. If the policy does not specify a ParamKind then this field is ignored, and the rules are evaluated without a param.
		///
		public var paramRef: admissionregistration.v1alpha1.ParamRef?
		///
		/// policyName references a MutatingAdmissionPolicy name which the MutatingAdmissionPolicyBinding binds to. If the referenced resource does not exist, this binding is considered invalid and will be ignored Required.
		///
		public var policyName: String?
		///
		/// Default memberwise initializer
		///
		public init(
			matchResources: admissionregistration.v1alpha1.MatchResources? = nil,
			paramRef: admissionregistration.v1alpha1.ParamRef? = nil,
			policyName: String? = nil
		) {
			self.matchResources = matchResources
			self.paramRef = paramRef
			self.policyName = policyName
		}
	}
}

///
/// Codable conformance
///
public extension admissionregistration.v1alpha1.MutatingAdmissionPolicyBindingSpec {

	private enum CodingKeys: String, CodingKey {

		case matchResources = "matchResources"
		case paramRef = "paramRef"
		case policyName = "policyName"
	}

	init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		self.matchResources = try container.decodeIfPresent(admissionregistration.v1alpha1.MatchResources.self, forKey: .matchResources)
		self.paramRef = try container.decodeIfPresent(admissionregistration.v1alpha1.ParamRef.self, forKey: .paramRef)
		self.policyName = try container.decodeIfPresent(String.self, forKey: .policyName)
	}

	func encode(to encoder: Encoder) throws {
		var encodingContainer = encoder.container(keyedBy: CodingKeys.self)

		try encodingContainer.encode(matchResources, forKey: .matchResources)
		try encodingContainer.encode(paramRef, forKey: .paramRef)
		try encodingContainer.encode(policyName, forKey: .policyName)
	}
}
