//
// Copyright 2020 Swiftkube Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

///
/// Generated by Swiftkube:ModelGen
/// Kubernetes v1.28.3
/// networking.v1alpha1.IPAddressSpec
///

import Foundation

// MARK: - networking.v1alpha1.IPAddressSpec

public extension networking.v1alpha1 {

	///
	/// IPAddressSpec describe the attributes in an IP Address.
	///
	struct IPAddressSpec: KubernetesResource {
		///
		/// ParentRef references the resource that an IPAddress is attached to. An IPAddress must reference a parent object.
		///
		public var parentRef: networking.v1alpha1.ParentReference?
		///
		/// Default memberwise initializer
		///
		public init(
			parentRef: networking.v1alpha1.ParentReference? = nil
		) {
			self.parentRef = parentRef
		}
	}
}

///
/// Codable conformance
///
public extension networking.v1alpha1.IPAddressSpec {

	private enum CodingKeys: String, CodingKey {

		case parentRef = "parentRef"
	}

	init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		self.parentRef = try container.decodeIfPresent(networking.v1alpha1.ParentReference.self, forKey: .parentRef)
	}

	func encode(to encoder: Encoder) throws {
		var encodingContainer = encoder.container(keyedBy: CodingKeys.self)

		try encodingContainer.encode(parentRef, forKey: .parentRef)
	}
}
